# Generated by Django 2.1.7 on 2020-07-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=100000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fixed_to_top', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('WS', 'Водогосподарська обстановка'), ('EV', 'Еколого-просвітницькі заходи'), ('MR', 'Управління річковими басейнами')], max_length=10, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
