# Generated by Django 2.0.7 on 2020-07-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('WS', 'Водогосподарська обстановка'), ('EV', 'Еколого-просвітницькі заходи'), ('MR', 'Управління річковими басейнами')], max_length=10, null=True),
        ),
    ]
