# Generated by Django 2.0.7 on 2020-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200704_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
