# Generated by Django 2.0.7 on 2020-07-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200702_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
