# Generated by Django 2.0.7 on 2020-07-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200703_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=100000),
        ),
    ]
